import { useState } from 'react'
import { motion } from 'motion/react'
import { Plus, Search } from 'lucide-react'
import { useAuth } from '../../context/AuthContext'
import { useHR } from '../../context/HRContext'
import { departments, isManager } from '../../data/mockData'
import EmployeeCard from '../../components/employees/EmployeeCard'
import Button from '../../components/ui/Button'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '../../components/ui/Dialog'
import { stagger } from '../../lib/motion'

export default function TeamDashboard() {
  const { user } = useAuth()
  const { team, createEmployee } = useHR()
  const [search, setSearch] = useState('')
  const [dept, setDept] = useState('')
  const [open, setOpen] = useState(false)
  const [created, setCreated] = useState(null)
  const [form, setForm] = useState({
    firstName: '', lastName: '', email: '', phone: '', role: 'EMPLOYEE', department: 'Engineering', designation: '', dateOfJoining: new Date().toISOString().slice(0, 10), wage: '50000',
  })

  const filtered = team.filter((emp) => {
    const q = search.toLowerCase()
    const matches = !q || `${emp.firstName} ${emp.lastName} ${emp.email} ${emp.loginId}`.toLowerCase().includes(q)
    return matches && (!dept || emp.department === dept)
  })

  const submit = (e) => {
    e.preventDefault()
    const result = createEmployee(form)
    setCreated(result)
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
        <div>
          <p className="text-sm font-medium text-primary">Good {new Date().getHours() < 12 ? 'morning' : 'afternoon'}, {user.firstName}</p>
          <h1 className="mt-1 text-3xl font-extrabold tracking-tight md:text-4xl">Your team, in flow</h1>
          <p className="mt-1 text-sm text-ink-muted">Click a card to open employee information in view-only mode.</p>
        </div>
        {isManager(user.role) && (
          <Button className="gap-2" onClick={() => { setCreated(null); setOpen(true) }}>
            <Plus className="h-4 w-4" /> Add employee
          </Button>
        )}
      </div>

      <div className="flex flex-col gap-3 sm:flex-row">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-ink-faint" />
          <input className="input pl-10" placeholder="Search people, email, or login ID" value={search} onChange={(e) => setSearch(e.target.value)} />
        </div>
        <select className="input sm:w-48" value={dept} onChange={(e) => setDept(e.target.value)}>
          <option value="">All departments</option>
          {departments.map((d) => <option key={d}>{d}</option>)}
        </select>
      </div>

      <motion.div variants={stagger} initial="initial" animate="animate" className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        {filtered.map((emp) => (
          <EmployeeCard key={emp.id} employee={emp} />
        ))}
      </motion.div>

      <Dialog open={open} onClose={() => setOpen(false)}>
        <DialogContent onClose={() => setOpen(false)} className="mx-4">
          <DialogHeader>
            <DialogTitle>{created ? 'Employee created' : 'Create employee'}</DialogTitle>
          </DialogHeader>
          {created ? (
            <div className="space-y-3 p-6 pt-0">
              <p className="text-sm text-ink-muted">Login ID is generated by the system. The first password is the same Login ID until they change it.</p>
              <div className="rounded-xl bg-cream p-4 font-mono text-sm">
                <p>Login ID: {created.employee.loginId}</p>
                <p>Email: {created.employee.email}</p>
                <p>First password: {created.password}</p>
              </div>
              <DialogFooter>
                <Button onClick={() => setOpen(false)}>Done</Button>
              </DialogFooter>
            </div>
          ) : (
            <form onSubmit={submit}>
              <div className="grid grid-cols-2 gap-3 p-6 pt-0">
                <input required className="input" placeholder="First name" value={form.firstName} onChange={(e) => setForm({ ...form, firstName: e.target.value })} />
                <input required className="input" placeholder="Last name" value={form.lastName} onChange={(e) => setForm({ ...form, lastName: e.target.value })} />
                <input required type="email" className="input col-span-2" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} />
                <input className="input col-span-2" placeholder="Phone" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} />
                <select className="input" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}>
                  <option value="EMPLOYEE">Employee</option>
                  <option value="HR">HR Officer</option>
                  <option value="ADMIN">Admin</option>
                </select>
                <select className="input" value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })}>
                  {departments.map((d) => <option key={d}>{d}</option>)}
                </select>
                <input className="input" placeholder="Designation" value={form.designation} onChange={(e) => setForm({ ...form, designation: e.target.value })} />
                <input type="date" className="input" value={form.dateOfJoining} onChange={(e) => setForm({ ...form, dateOfJoining: e.target.value })} />
                <input className="input col-span-2" placeholder="Monthly wage" value={form.wage} onChange={(e) => setForm({ ...form, wage: e.target.value })} />
              </div>
              <DialogFooter>
                <Button variant="secondary" type="button" onClick={() => setOpen(false)}>Cancel</Button>
                <Button type="submit">Create</Button>
              </DialogFooter>
            </form>
          )}
        </DialogContent>
      </Dialog>
    </div>
  )
}
